handlebars:
  suffix: .html

server:
  tomcat:
    accept-count: 1
    max-connections: 1
    threads:
      max: 2
      min-spare: 2
spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
